apiVersion: v1
kind: Service
metadata:
  name: apacheds
  labels:
    app: apacheds
spec:
  ports:
  - port: 10389
    targetPort: 10389
    name: ldap
  selector:
    app: apacheds
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apacheds
spec:
  selector:
    matchLabels:
      app: apacheds
  replicas: 1
  template:
    metadata:
      labels:
        app: apacheds
    spec:
      containers:
      - name: apacheds
        image: 002125563322.dkr.ecr.us-west-2.amazonaws.com/archnav-ldap:latest
        ports:
        - containerPort: 10389
          name: ldap