apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    app: mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: 002125563322.dkr.ecr.us-west-2.amazonaws.com/archnav-mysql:latest
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: password
        - name: MYSQL_DATABASE
          value: archemy
        - name: MYSQL_USER
          value: archnav
        - name: MYSQL_PASSWORD
          value: archnav
        ports:
        - containerPort: 3306
          name: mysql